services:
  postgres:
    image: postgres:latest
    # build: ./requirements/postgres/. - 배포시 스크립트 수정해서 사용
    container_name: postgres
    shm_size: 256mb
    # TODO: 환경변수로 설정
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intra
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - intra
    restart: always

  # 개발중이면 도커 사용 안함
  # django:
  #   build: ./backend/.
  #   container_name: django
  #   command: python manage.py runserver
  #   networks:
  #     - intra
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   restart: always

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/${USER}/postgres_data

networks:
  intra:
    driver: bridge