FROM alpine:3.19 as base

# Set build arguments
ARG BUILD_ARCH="x86_64"
ARG USER_NAME=appuser
ARG USER_ID=1000
ARG GROUP_NAME=appgroup
ARG GROUP_ID=1000
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1 \
PIP_DISABLE_PIP_VERSION_CHECK=1 \
PIP_NO_CACHE_DIR=1
# Set working directory
WORKDIR /app/
# Install dumb-init
ADD --chmod=755 https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_${BUILD_ARCH} /bin/dumb-init
# Create a non-root user and set permissions
RUN addgroup --gid $GROUP_ID $GROUP_NAME \
    && adduser --disabled-password \
                --ingroup $GROUP_NAME \
                --no-create-home \
                --uid $USER_ID \
                $USER_NAME
# Install base dependencies
ARG BASE_DEPS="python3"
RUN apk add --update --no-cache ${BASE_DEPS}
RUN mkdir -p /var/www/ft/
RUN chown -R ${USER_NAME}:${GROUP_NAME} /var/www/ft/
# Set builder image
FROM base as builder
# Set working directory
WORKDIR /app/
# Install build dependencies
ARG BUILD_DEPS="gcc musl-dev libffi-dev python3-dev"
RUN --mount=type=bind,source=pyproject.toml,target=/app/pyproject.toml \
    apk add --no-cache ${BUILD_DEPS} \
    && python3 -m venv /app/venv \
    && /app/venv/bin/pip install setuptools \
    && /app/venv/bin/pip install /app \
    && apk del ${BUILD_DEPS}


# Set runtime image
FROM base as runtime
# Set working directory
WORKDIR /app/
# Set non-root user
USER ${USER_NAME}
# Set environment variables
ENV VIRTUAL_ENV="/app/venv" \
PATH="/app/venv/bin:$PATH"
# Copy the virtual environment from the builder image
COPY --from=builder --chown=$USER_ID:$GROUP_ID /app/venv /app/venv
# Copy source and entrypoint
COPY --chown=$USER_ID:$GROUP_ID . /app
COPY --chown=$USER_ID:$GROUP_ID --chmod=755 ./entrypoint.sh /app/entrypoint.sh
# Expose port 8000
EXPOSE 8000
# Test and run daphne
ENTRYPOINT [ "/bin/dumb-init", "--" ]
CMD ["/app/entrypoint.sh"]

# Healthcheck
# HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
#     CMD curl --fail http://localhost:8000/ || exit 1