# 개발중에는 안씀
FROM alpine:3.18

# RUN apk add --no-cache python3 py3-pip 

# COPY requirements.txt /tmp/requirements.txt

# RUN pip install --no-cache-dir -r /tmp/requirements.txt

# ENTRYPOINT [ "executable" ]