FROM alpine:3.19

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PATH="/app/venv/bin:$PATH"

# Set the working directory and copy contents into the container at /app
WORKDIR /app
ADD . /app

# Install python3 and dependencies
RUN apk add --update --no-cache python3 \
    python3-dev \
    libffi-dev \
    build-base \
    && python3 -m venv /app/venv \
    && /app/venv/bin/pip install --upgrade pip \
    && /app/venv/bin/pip install -r /app/requirements.txt \
    && apk del build-base python3-dev libffi-dev

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Test and run daphne
CMD ["/bin/sh", "/app/entrypoint.sh"]