"""
Django settings for ft_transcendence project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from corsheaders.defaults import default_methods, default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


def load_dotenv(file_path):
    with open(file_path) as f:
        for line in f:
            # Remove leading/trailing whitespace
            line = line.strip()
            # Ignore comments and empty lines
            if line.startswith("#") or not line:
                continue
            # Split at the first `=` character
            key, value = line.split("=", 1)
            # Remove leading/trailing whitespace from key and value
            key = key.strip()
            value = value.strip()
            # Set the environment variable
            os.environ[key] = value


# TODO: 배포시 False로 변경
DEBUG = True

if DEBUG:
    load_dotenv(os.path.join(BASE_DIR, "../../.env"))

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# TODO: 나중에 환경변수로 변경
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:5500",
    "http://localhost:8000",
    "http://localhost:8080",
]
CSRF_COOKIE_SECURE = False  # 개발시에는 False로 설정
CSRF_COOKIE_SAMESITE = "Lax"
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:5500",
    "http://localhost:8000",
    "http://localhost:8080",
]

CORS_ALLOW_METHODS = [
    *default_methods,
]

CORS_ALLOW_HEADERS = (
    *default_headers,
    "access-control-allow-origin",
    "origin",
)


# Application definition

INSTALLED_APPS = [
    "daphne",  # daphne - ASGI 서버
    "corsheaders",  # cors - cross-origin resource sharing
    "ft_transcendence",  # 프로젝트 설정
    "api",  # api 라우팅
    "ws",  # websocket 라우팅
    "oauth",  # 42 OAuth
    "user",  # 유저 관리
    # "pong",  # 게임 관리
    "lobby",  # 로비 관리
    "channels",  # channels - websocket
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware", - 임시로 CSRF 보안 비활성화
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ft_transcendence.urls"
CHANNEL_URLCONF = "ft_transcendence.routing"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "../frontend/"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ft_transcendence.wsgi.application"
ASGI_APPLICATION = "ft_transcendence.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# TODO: 나중에 환경변수로 변경
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ft_transcendence",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "localhost",  # PostgreSQL이 로컬에 설치된 경우
        "PORT": "5432",  # 기본 PostgreSQL 포트
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = "user.User"

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False  # 개발시에는 False로 설정


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "../frontend/"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

CHANNEL_LAYERS = {
    "default": {
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}


# 42 OAuth
OAUTH_42_URL = "https://api.intra.42.fr/oauth/authorize"
OAUTH_42_CLIENT_ID = os.getenv("OAUTH_42_CLIENT_ID")
OAUTH_42_CLIENT_SECRET = os.getenv("OAUTH_42_CLIENT_SECRET")
OAUTH_42_REDIRECT_URI = "http://localhost:8000/oauth/callback/"
OAUTH_42_TOKEN_URL = "https://api.intra.42.fr/oauth/token"
